### ISSUE TITLE
Customize the close button text

### ISSUE THREAD

**Issue by Dorianspeed** [harshzalavadiya/react-web-share#10]
Hello :wave: !

I wanted to know if there is any possibility to get a props (eg: closeTitle) attached to RWebShare component for customizing the close button text ?

Thx in advance for your answer ! :wink:

**Comment by harshzalavadiya** [comment]
@Dorianspeed I think it should be possible, I'll add customization soon

**Comment by snavaneeth78** [comment]
Would be also great, if we can provide custom icons. Thanks for the great work!

**Comment by harshzalavadiya** [comment]
@snavaneeth78 I have created #12 seprately  to track it since it's different feature request

**Comment by harshzalavadiya** [comment]
@Dorianspeed I have added this feature in `v1.0.18`
