### ISSUE TITLE
Completion or init callback

### ISSUE THREAD

**Issue by croossin** [harshzalavadiya/react-web-share#14]
Would be great to know if/when the user taps on this and has shared.

**Comment by harshzalavadiya** [comment]
good idea, will try to add this soon

**Comment by rohan-deshpande** [comment]
Really need this feature, would this be as simple as adding an `onShare` prop that's a function and call this inside the `onClick` handler?

**Comment by harshzalavadiya** [comment]
released `v1.1.0`
