### ISSUE TITLE
WhatsApp links are broken

### ISSUE THREAD

**Issue by joshsny** [harshzalavadiya/react-web-share#19]
Whatsapp links use the url https://api.whatsapp.com which doesn't work, shouldn't it be https://web.whatsapp.com instead?

**Comment by harshzalavadiya** [comment]
@joshsny api.whatsapp.com can trigger opeing mobile application if you visit from mobile device / web.whatsapp.com is external interface which is different
---
every share service will trigger this check this out for example
https://www.addthis.com/examples/share-buttons/floating-bar/

**Comment by joshsny** [comment]
My bad 🤦‍♂️
