### ISSUE TITLE
"option" property is actually "sites"

### ISSUE THREAD

**Issue by cbourlon** [harshzalavadiya/react-web-share#2]
Hey @harshzalavadiya, Thank you for this amazing package. I'm very happy to be able to use it. 
I just wanted to flag that the "option" prop described in the readme is actually "sites". 

For example
```jsx
<div className="share-button-container">
  <RWebShare
    data={{
      text: "texte",
      url: window.location.href,
      title: "title",
    }}
    sites={["facebook", "whatsapp", "mail", "copy"]}
  >
    <button className="share-button">Share the message</button>
  </RWebShare>
</div>
```

Also, I was wondering if there was a way to custom the style of the fallback? I'd like to change the colors and the icons but I'm not sure what's the best way to proceed...

Again, thank you very much for your work. 

Have a nice one!

**Comment by harshzalavadiya** [comment]
@cbourlon 

Thanks for pointing out the wrong prop and I'm glad you liked the package,
Currently There's no way to customize icons and colors, but I think having this flexiblity might be a very good idea, I'll add this as soon as I get some free time from my regular work

**Comment by cbourlon** [comment]
@harshzalavadiya, It sounds very good!

Thanks for your answer. Keep up the niceness ;)
