### ISSUE TITLE
add other vendors

### ISSUE THREAD

**Issue by avesgit** [harshzalavadiya/react-web-share#22]
add plz Vk.com ok.ru tiktok

**Comment by harshzalavadiya** [comment]
@avesgit 

I guess tiktok doesn't provide share via web

I've added vk and ok in new version, here's example

https://codesandbox.io/s/react-web-share-localized-xmvmzl

**Comment by avesgit** [comment]
> @avesgit
> 
> I guess tiktok doesn't provide share via web
> 
> I've added vk and ok in new version, here's example
> 
> https://codesandbox.io/s/react-web-share-localized-xmvmzl

Матн ерфтлы
