### ISSUE TITLE
Missing URL encoding for Links with parameters by sharing on Facebook and Whatsapp 

### ISSUE THREAD

**Issue by gallifilo** [harshzalavadiya/react-web-share#4]
For instance I would like to share this url [https://canitravel.net/countries/?from=176&passport=176](https://canitravel.net/countries/?from=176&passport=176)
as you can see there are _from_ and _passport_ as parameters in the above link

on whatsapp the request made would be

[https://api.whatsapp.com/send?text=https://canitravel.net/countries/?from=176&passport=176](https://api.whatsapp.com/send?text=https://canitravel.net/countries/?from=176&passport=176)

which results in `https://canitravel.net/countries/?from=176`, missing the _passport_ parameter

I think it would be only a matter of encoding the url in the text parameter of the request to whatsapp.

What do you think, would it be possible? 
 

Thanks, 

Super nice component by the way!

**Comment by harshzalavadiya** [comment]
@gallifilo 

Good catch, I'll try to fix it in a day or two

**Comment by harshzalavadiya** [comment]
Fixed in `v1.0.9`
