### ISSUE TITLE
Copying the link to the clipboard button copies a Url encoded version of the link.

### ISSUE THREAD

**Issue by gallifilo** [harshzalavadiya/react-web-share#6]
Pressing on this button to copy the link to share
<img width="111" alt="Screenshot 2020-10-19 at 14 45 44" src="https://user-images.githubusercontent.com/9945276/96459230-cc89d700-1219-11eb-9cea-94d54210d564.png">
it copies the link encoded in url format.

so for instance, _https://canitravel.net/countries?from=portugal&passport=portugal&sort=open_
becomes 
_https%3A%2F%2Fcanitravel.net%2Fcountries%2F%3Ffrom%3Dportugal%26passport%3Dportugal%26sort%3Dopen_

**Comment by harshzalavadiya** [comment]
@gallifilo Thanks for reporting this

Resolved in `v1.0.13`
